// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQpbNzXFhWQizn_eHy4Ojcp1PwgDiuhGw',
    appId: '1:527888668710:web:b1cd00452df638d971eee7',
    messagingSenderId: '527888668710',
    projectId: 'gym-app-62a8f',
    authDomain: 'gym-app-62a8f.firebaseapp.com',
    storageBucket: 'gym-app-62a8f.appspot.com',
    measurementId: 'G-SJBZXZXLRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfhcc2ynose7ii1NNnBb8d-0OtI-i2S_s',
    appId: '1:527888668710:android:83ed65a3506d318571eee7',
    messagingSenderId: '527888668710',
    projectId: 'gym-app-62a8f',
    storageBucket: 'gym-app-62a8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvfc_o8zHsrlYUCEBzpadHl2njfi3pVUI',
    appId: '1:527888668710:ios:a08e4a0cee0e1a0f71eee7',
    messagingSenderId: '527888668710',
    projectId: 'gym-app-62a8f',
    storageBucket: 'gym-app-62a8f.appspot.com',
    iosBundleId: 'com.example.volt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvfc_o8zHsrlYUCEBzpadHl2njfi3pVUI',
    appId: '1:527888668710:ios:a08e4a0cee0e1a0f71eee7',
    messagingSenderId: '527888668710',
    projectId: 'gym-app-62a8f',
    storageBucket: 'gym-app-62a8f.appspot.com',
    iosBundleId: 'com.example.volt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQpbNzXFhWQizn_eHy4Ojcp1PwgDiuhGw',
    appId: '1:527888668710:web:f65f2d65d59e2dda71eee7',
    messagingSenderId: '527888668710',
    projectId: 'gym-app-62a8f',
    authDomain: 'gym-app-62a8f.firebaseapp.com',
    storageBucket: 'gym-app-62a8f.appspot.com',
    measurementId: 'G-ZR0BT760N2',
  );

}